name: mn-protein-design

services:
  scannet:
    image: mn-scannet:cpu
    build:
      context: .
      dockerfile: ../mn-tool-containers/protein-design/scannet/Dockerfile
      platforms: ["linux/x86_64"]

  surf2spot:
    image: mn-surf2spot:cu128
    build:
      context: .
      dockerfile: ../mn-tool-containers/protein-design/surf2spot/Dockerfile
      platforms: ["linux/x86_64"]
      args:
        INSTALL_ESMFOLD: "false"

  pesto:
    image: mn-pesto:cu128
    build:
      context: ../ovo-ligand
      dockerfile: ../mn-tool-containers/shared/pesto/Dockerfile
      platforms: ["linux/x86_64"]
    gpus: all

  masif-seed:
    image: mn-masif-seed:cpu
    build:
      context: tools_to_implement/masif_seed
      dockerfile: ../../../mn-tool-containers/protein-design/masif-seed/Dockerfile
      platforms: ["linux/x86_64"]

  genie3:
    image: mn-genie3:cu128
    build:
      context: .
      dockerfile: ../mn-tool-containers/protein-design/genie3/Dockerfile
      platforms: ["linux/x86_64"]
      args:
        DOWNLOAD_WEIGHTS: "false"
        DOWNLOAD_TRAINING_DATA: "false"

  pxdesign:
    image: mn-pxdesign:cu128
    build:
      context: .
      dockerfile: ../mn-tool-containers/protein-design/pxdesign/Dockerfile
      platforms: ["linux/x86_64"]

  protenix:
    image: mn-protenix:cu128
    build:
      context: .
      dockerfile: ../mn-tool-containers/protein-design/protenix/Dockerfile
      platforms: ["linux/x86_64"]
    gpus: all
    volumes:
      - /mnt/db/reference_files/protenix:/ref/protenix:rw

  protpardelle-1c:
    image: mn-protpardelle-1c:cu128
    build:
      context: .
      dockerfile: ../mn-tool-containers/protein-design/protpardelle-1c/Dockerfile
      platforms: ["linux/x86_64"]

  biohub-esm:
    image: mn-biohub-esm:cu128
    build:
      context: .
      dockerfile: ../mn-tool-containers/shared/biohub-esm/Dockerfile
      platforms: ["linux/x86_64"]
    gpus: all
    volumes:
      - biohub-esm-hf-cache:/cache/huggingface
      - /mnt/db/reference_files/biohub-esm:/ref/biohub-esm:ro

  colabfold:
    image: mn-colabfold:1.6.1-cu12
    build:
      context: .
      dockerfile: ../mn-tool-containers/protein-design/colabfold/Dockerfile
      platforms: ["linux/x86_64"]

  openfold3:
    image: mn-openfold3:cu13
    build:
      context: .
      dockerfile: ../mn-tool-containers/protein-design/openfold3/Dockerfile
      platforms: ["linux/x86_64"]
      args:
        PIXI_ENV: openfold3-cuda13
    gpus: all
    volumes:
      - /mnt/db/reference_files/openfold3:/ref/openfold3:rw

  ligandmpnn:
    image: mn-ligandmpnn:latest

  foundry-cu128:
    image: mn-foundry:cu128

volumes:
  biohub-esm-hf-cache:
