name: mn-protein-design
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - biopython
  - pdbfixer
  - pymol-open-source
  - pyyaml
  - openjdk=17
  - nextflow
  - openpyxl
  - streamlit
  - typer
  - pip
  - pip:
      - -e .
