FROM mnprot-protpardelle-1c-cu128:pre-foldseek

RUN wget -q https://mmseqs.com/foldseek/foldseek-linux-gpu.tar.gz \
    && tar -xzf foldseek-linux-gpu.tar.gz -C /opt \
    && rm foldseek-linux-gpu.tar.gz \
    && ln -sf /opt/foldseek/bin/foldseek /usr/local/bin/foldseek

ENV FOLDSEEK_BIN=/opt/foldseek/bin/foldseek
